### ISSUE TITLE
inventory.filter is not a function

### ISSUE THREAD

**Issue by amerwin724** [Heimdall-Industries/Heidrun#5]
When I try to run the program I get:
```
 ------- INVENTORY -------
TypeError: inventory.filter is not a function
    at Write.printAvailableSupply (C:\Users\kains\staratlas-automation\lib\write.js:136:34)
    at start (C:\Users\kains\staratlas-automation\start.js:196:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I'm not really sure what this means so I am not sure how to start troubleshooting it...

**Comment by amerwin724** [comment]
nvm, I figured it out.  I updated my modules, but didn't update start.js to match.
